version: "3.8"
services:
    web:
        container_name: app
        restart: always
        build:
            context: .
        ports:
            - "3000:3000"
        volumes:
            - ./:/app
            - /app/node_modules